steps:
    # Build the container image
    - name: 'Building container image'
      args: ['build', '-t', 'gcr.io/tenseconds-b5f56/pizza-app', '.']
    # Push the image to Container Registry
    - name: 'Push image to the Container Registry'
      args: ['push', 'gcr.io/tenseconds-b5f56/pizza-app']
    # Deploy image to Cloud Run
    - name: 'Deploy image to Cloud Run'
      args: ['run', 'deploy', 'angular-ssr', '--image', 'gcr.io/tenseconds-b5f56/pizza-app', '--region', 'europe-west1', '--platform', 'managed', '--allow-unauthenticated']
images:
    - gcr.io/tenseconds-b5f56/pizza-app
